name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Clone ParticleZoo repository
      uses: actions/checkout@v4
      
    - name: Install ROOT framework
      run: sudo snap install root-framework
      
    - name: Build and install ParticleZoo library
      run: |
        ./configure
        make
        sudo make install

    - name: Verify installation
      run: |
        PHSPImage --version
        PHSPCombine --version
        PHSPConvert --version
        PHSPSplit --version

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Clone ParticleZoo repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build and install ParticleZoo library
      run: |
        .\build.bat install
        setx PATH "%PATH%;C:\Users\runneradmin\AppData\Local\particlezoo\bin"

    - name: Verify installation
      run: |
        PHSPImage --version
        PHSPCombine --version
        PHSPConvert --version
        PHSPSplit --version